# Generated by Django 5.0.6 on 2024-05-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rate_plants',
            field=models.IntegerField(max_length=10),
        ),
    ]
