# Generated by Django 5.0.6 on 2024-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_page', '0003_alter_report_rate_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='sowing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
