# Generated by Django 5.0.6 on 2024-05-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_page', '0004_greenhouse_sowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='energy_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
