# Generated by Django 5.0.6 on 2024-05-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_page', '0005_registry_energy_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts_gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts_type', models.CharField(choices=[('Температура', 'Температура'), ('Влажность', 'Влажность'), ('Вода', 'Вода'), ('Освещение', 'Освещение'), ('Оборудование', 'Оборудование'), ('Ошибка', 'Ошибка')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse_page.greenhouse')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
            },
        ),
    ]
