# Generated by Django 5.0.6 on 2024-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_page', '0006_alerts_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
